block-list-secret-scan: []
branch: main
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - terraform
  - terraform_plan
secrets-scan-file-type: []
summary-position: top
output:
  - sarif
  - cli
output-file-path: reports/
