name: "Checkov"
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          output_file_path: reports/results.sarif

      - name: ls
        run: |
          ls
          ls reports

      - uses: actions/upload-artifact@v3
        name: Upload Checkov results artifacts
        with:
          name: checkov.report
          path: reports/
