name: "Development: CI/CD pipeline"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_WORKSPACE_DEV: "default"

jobs:
  checkov:
    name: Run Checkov code analysis
    uses: ./.github/workflows/checkov.yml

  terraform-apply:
    name: Apply Terraform Plan
    needs: checkov
    uses: ./.github/workflows/terraform.apply.yml
    with:
      terraform_workspace: default
      terraform_plan_args: "-var-file ./variables.dev.tfvars"
      github_environment: Development
    secrets: inherit
